config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root 'searches#index'

  resources :searches do
    collection do
      post :search_analytics
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  def self.title_search(query)
    self.where('title LIKE ?', "%#{query}%")
  end
end

app/models/search.rb
class Search < ApplicationRecord

  validates_presence_of :query

  def self.analytics_search(query, user_ip)
    self.where('query LIKE ? and user_ip = ?', "%#{query}%", "#{user_ip}")
        .select('query, user_ip, count(*) as count_order')
        .group('query, user_ip')
        .order('count_order DESC')
        .limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    @search = Search.new(user_ip: request.remote_ip)
    @search_results = []
    @analytics = []
  end

  def create
    @search = Search.new(search_params)
    @search.save

    @search_results = Article.title_search(@search.query)

    render turbo_stream: turbo_stream.update("search_results", partial: 'searches/results', locals: { search_results: @search_results })
  end

  def search_analytics
    @analytics = Search.analytics_search(params[:query], request.remote_ip)

    render turbo_stream: turbo_stream.update("analytics_results", partial: 'searches/analytics', locals: { analytics: @analytics })
  end

  private
  def search_params
    params.require(:search).permit(:query, :user_ip)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Realtime Search" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/searches/_analytics.html.erb
<div class="mt-2">
  <% @analytics.each do |analytic| %>
    <div
      data-action="click->analytics#search_suggestion"
      class="p-2 mb-1 bg-gray-100 hover:bg-gray-200 cursor-pointer rounded-md">
      <%= button_to analytic.query, class: "w-full text-left cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/searches/_form.html.erb
<%= form_with(model: @search, method: :post, data: { target_url: search_analytics_searches_path, submit_target: 'form', controller: 'analytics', action: 'keyup->analytics#suggest' }) do |form| %>
  <div class="relative mb-6 flex items-center">
    <div class="flex-grow">
      <%= form.label :query, "Search Query", class: "block mb-2 text-sm font-medium text-gray-700" %>
      <%= form.text_field :query, id: "input_bar", class: "w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition", placeholder: "Type your search...", data: { analytics_target: "input" } %>
    </div>
    <%= form.submit "Search", class: "btn btn-primary bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md shadow-md transition ml-2" %>
  </div>
  <div id="analytics_results" data-analytics-target="suggestions" class="absolute z-10 w-full bg-white border border-gray-300 rounded-md mt-1 hidden">
    <%= render 'analytics' %>
  </div>

  <%= form.hidden_field :user_ip, value: @search.user_ip %>
<% end %>

app/views/searches/_results.html.erb
<ul class="list-group">
  <% @search_results.each do |result| %>
    <li class="list-group-item">
      <strong><%= result.title %></strong>
      <p><%= truncate(result.body, length: 100) %></p>
      <p><em>Published at: <%= result.created_at.strftime("%B %d, %Y") if result.created_at %></em></p>
    </li>
  <% end %>
</ul>

app/views/searches/index.html.erb
<div>
  <%= render 'form' %>
</div>
<div id="search_results">
  <%= render 'results' %>
</div>